### ISSUE TITLE
license

### ISSUE THREAD

**Issue by MehdiK** [srkirkland/Inflector#3]
Hi,

I would like to incorporate Inflector's functionality into [Humanizer](https://github.com/MehdiK/Humanizer) and was wondering to know what's the license for Inflector.

I could take a nuget dependency on it but it would be ideal if I could just copy the code  in.

**Comment by srkirkland** [comment]
Good point -- I'll add a license to this project and let you know. Probably MIT, so you can basically do anything you want with the code.

**Comment by MehdiK** [comment]
MIT would be awesome :) Thanks.

**Comment by srkirkland** [comment]
@MehdiK Done- MIT licence is in the root of the project now.  Enjoy!

**Comment by MehdiK** [comment]
Thanks

**Comment by hazzik** [comment]
It seems that inflector's original license is Apache 2.0 license.

More details is here.
http://web.archive.org/web/20080502014626/http://andrewpeters.net/inflectornet/ (the site is dead).
http://meta.stackexchange.com/a/61405/168767

On re-licensing Apache 2.0 to MIT: http://stackoverflow.com/a/8448970/259946
